name: Push image to ghcr.io

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push multiarch image
        env:
          SHORT_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${SHORT_SHA::7}
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 --push \
            -t ghcr.io/voidcontests/web:$SHORT_SHA \
            -t ghcr.io/voidcontests/web:latest .
